import type {LearningUnit,MappingLink,PracticeActivity} from '../../domain/content/types.ts';
import {effectiveApprovalState} from '../governance/approvals.ts';
export type Beta3Disposition='existing-engine'|'needs-capability'|'needs-content'|'remap-required';
export interface Beta3CapabilityRow{learningUnitId:string;legacyId:string;grade:11;primaryPracticeId:string;disposition:Beta3Disposition;requiredCapabilities:string[]}
export interface Beta3ReadinessInput{units:LearningUnit[];practices:PracticeActivity[];mappings:MappingLink[];matrix:Beta3CapabilityRow[];configRegistry:Record<string,unknown>}
function pending(p:PracticeActivity){const approvals=effectiveApprovalState(p as any);const out:string[]=[];if(approvals.technical.status!=='approved')out.push('technical');if(approvals.didactic.status!=='approved')out.push('didactic');if(approvals.accessibility.status!=='approved')out.push('accessibility');if(approvals.chemistry!=='not_applicable'&&approvals.chemistry.status!=='approved')out.push('chemistry');return out;}
function reason(d:Beta3Disposition){return d==='needs-capability'?'CAPABILITY_PENDING':d==='needs-content'?'CONTENT_GAP':d==='remap-required'?'REMAP_REQUIRED':undefined;}
export function buildBeta3ReadinessReport(input:Beta3ReadinessInput){
 const units=new Map(input.units.filter(u=>u.grade===11).map(u=>[u.id,u]));const practices=new Map(input.practices.map(p=>[p.id,p]));const primary=new Map<string,MappingLink>();
 for(const m of input.mappings){if(m.role!=='primary'||!units.has(m.learningUnitId))continue;if(primary.has(m.learningUnitId))throw new Error(`BETA3_PRIMARY_MAPPING_DUPLICATE:${m.learningUnitId}`);primary.set(m.learningUnitId,m);}
 if(input.matrix.length!==units.size)throw new Error(`BETA3_MATRIX_COVERAGE_MISMATCH:${input.matrix.length}:${units.size}`);
 const rows=input.matrix.map(cap=>{const unit=units.get(cap.learningUnitId);if(!unit)throw new Error(`BETA3_MATRIX_UNIT_UNKNOWN:${cap.learningUnitId}`);const mapping=primary.get(unit.id);const reasons:string[]=[];if(!mapping)reasons.push('PRIMARY_MAPPING_MISSING');else if(mapping.practiceActivityId!==cap.primaryPracticeId)reasons.push('PRIMARY_MAPPING_DRIFT');const practice=mapping?practices.get(mapping.practiceActivityId):undefined;if(!practice)reasons.push('PRACTICE_MISSING');const blocked=reason(cap.disposition);if(blocked)reasons.push(blocked);if(cap.disposition==='existing-engine'){if(mapping&&mapping.coverageStatus!=='full')reasons.push('MAPPING_NOT_FULL');if(practice&&practice.lifecycleStatus!=='ready')reasons.push('ACTIVITY_NOT_READY');if(mapping&&!Object.prototype.hasOwnProperty.call(input.configRegistry,mapping.practiceActivityId))reasons.push('CONFIG_MISSING');if(practice&&practice.accessibilityProfile.length===0)reasons.push('ACCESSIBILITY_PROFILE_MISSING');if(practice&&practice.engineCompatibility.engine!==practice.type)reasons.push('ENGINE_COMPATIBILITY_MISMATCH');}const technicalReady=reasons.length===0;const approvalPending=practice?pending(practice):[];return {learningUnitId:unit.id,legacyId:cap.legacyId,disposition:cap.disposition,practiceActivityId:cap.primaryPracticeId,technicalReady,releaseReady:technicalReady&&approvalPending.length===0,reasons,approvalPending};});
 return {totalLearningUnits:rows.length,technicalReady:rows.filter(r=>r.technicalReady).length,releaseReady:rows.filter(r=>r.releaseReady).length,blockedByDisposition:{'needs-capability':rows.filter(r=>r.disposition==='needs-capability').length,'needs-content':rows.filter(r=>r.disposition==='needs-content').length,'remap-required':rows.filter(r=>r.disposition==='remap-required').length},rows};
}
