// KimyoLab HTTP server (P0.1 / P0.10 / P0.13).
//
// * Only the built deployment surface (PUBLIC_ROOT, default ./dist) is ever served.
//   Repository files (package.json, src/, scripts/, reports/, content-src/, ...) are
//   outside PUBLIC_ROOT and additionally not on the allow-list.
// * Static serving is allow-list based: known SPA routes, a few root files and a few
//   public prefixes with an extension allow-list. Everything else is 404.
// * API errors use {code,message,requestId}; external partner secrets never reach the browser.
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {validateExternalLabUrl, frameSourcesFor} from '../src/integrations/external-labs/url-policy.ts';
import {validateExternalLabBindings} from '../src/integrations/external-labs/registry.ts';
import {ApiError, apiError, HTTP_STATUS as S} from './http-errors.mjs';
import {createRateLimiter} from './rate-limit.mjs';
import {resolvePublicRoot as resolvePublicRootFromPaths} from './paths.mjs';

const TYPES = Object.freeze({
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.yaml': 'text/yaml; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
});
const ROOT_FILES = new Set(['/index.html', '/app.html']);
const PUBLIC_PREFIXES = ['/app-preview/', '/content/', '/assets/', '/vendor/nobook/'];
const SPA_EXACT = new Set(['/', '/curriculum', '/labs', '/progress', '/search']);
const SPA_PREFIXES = ['/learn/', '/practice/', '/worksheet/', '/external-lab/'];
const MAX_URL_LENGTH = 2048;
const SESSION_BODY_LIMIT = 4096;
const ID_PATTERNS = Object.freeze({
  bindingId: /^ext\.[a-z0-9.-]{1,80}$/,
  learningUnitId: /^lu\.(7|8|9|10|11)\.[0-9]+(\.[0-9]+)*$/,
  // Opaque anonymous installation id generated by the browser (UUID v4). Never PII.
  learnerRef: /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
});

/**
 * NOBOOK `unique_id` is the partner-side *user* identifier (docs/integrations/nobook-identity-contract.md).
 * It is derived server-side as a keyed HMAC of the anonymous installation id, so the partner gets a
 * stable pseudonym per learner installation that cannot be reversed or linked to KimyoLab data.
 */
export function deriveNobookUniqueId(learnerRef, key) {
  const digest = crypto.createHmac('sha256', key).update(`kimyolab.nobook.unique_id.v1:${learnerRef.toLowerCase()}`).digest('hex');
  return `kl_${digest.slice(0, 32)}`;
}

function sha256(buffer) { return crypto.createHash('sha256').update(buffer).digest('hex'); }

export function resolvePublicRoot(options = {}) {
  return resolvePublicRootFromPaths({cwd: options.cwd, publicRoot: options.publicRoot, env: options.env});
}

export function createKimyoLabServer(options = {}) {
  const env = options.env ?? process.env;
  const publicRoot = resolvePublicRoot({...options, env});
  if (!fs.existsSync(path.join(publicRoot, 'index.html'))) {
    const error = new Error(`PUBLIC_ROOT_NOT_BUILT: ${publicRoot} has no index.html. Run "npm run build" first.`);
    error.code = 'PUBLIC_ROOT_NOT_BUILT';
    throw error;
  }
  const realPublicRoot = fs.realpathSync(publicRoot);
  const log = options.logger ?? ((entry) => process.stdout.write(`${JSON.stringify(entry)}\n`));
  const limiters = {
    session: createRateLimiter({windowMs: 60_000, max: Number(env.KIMYOLAB_SESSION_RATE_LIMIT ?? 10), now: options.now}),
    status: createRateLimiter({windowMs: 60_000, max: Number(env.KIMYOLAB_STATUS_RATE_LIMIT ?? 60), now: options.now}),
  };
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;

  const csp = `default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-src ${frameSourcesFor('nobook').join(' ')}; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'`;
  const securityHeaders = {
    'Content-Security-Policy': csp,
    'X-Content-Type-Options': 'nosniff',
    'Referrer-Policy': 'no-referrer',
    'X-Frame-Options': 'DENY',
    'Cross-Origin-Opener-Policy': 'same-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
  };
  const headers = (extra = {}) => ({...securityHeaders, ...extra});

  // ---------- content pack helpers (server-side integrity as well) ----------
  function readPointer() {
    try { return JSON.parse(fs.readFileSync(path.join(publicRoot, 'content', 'manifest.json'), 'utf8')); } catch { return undefined; }
  }
  function servableContentVersions() {
    const pointer = readPointer();
    return new Set([pointer?.activeVersion, pointer?.previousVersion].filter((v) => typeof v === 'string'));
  }
  function loadActiveBindings() {
    const pointer = readPointer();
    if (!pointer || typeof pointer.activeVersion !== 'string' || !/^[A-Za-z0-9.-]+$/.test(pointer.activeVersion)) throw apiError(S.INTERNAL, 'CONTENT_POINTER_INVALID', 'Active content pointer is invalid.');
    const packDir = path.join(publicRoot, 'content', pointer.activeVersion);
    const manifest = JSON.parse(fs.readFileSync(path.join(packDir, 'manifest.json'), 'utf8'));
    const entry = (manifest.files ?? []).find((f) => f.path === 'external-lab-bindings.json');
    const bytes = fs.readFileSync(path.join(packDir, 'external-lab-bindings.json'));
    if (!entry || entry.checksum !== sha256(bytes)) throw apiError(S.INTERNAL, 'CONTENT_INTEGRITY_ERROR', 'Content file failed integrity verification.');
    return validateExternalLabBindings(JSON.parse(bytes.toString('utf8')));
  }

  // ---------- NOBOOK configuration (secrets stay on the server) ----------
  const nobookSdkPath = path.join(publicRoot, 'vendor', 'nobook', 'postmate.js');
  const nobookPartnerConfigured = () => Boolean(env.NOBOOK_APP_KEY && env.NOBOOK_APP_SECRET && env.NOBOOK_PID_SCOPE && env.NOBOOK_EXPERIMENT_URL);
  const nobookSdkReady = () => fs.existsSync(nobookSdkPath);
  const nobookSdkChecksumValid = () => {
    const expected = env.NOBOOK_SDK_SHA256;
    return Boolean(expected && /^[a-f0-9]{64}$/i.test(expected) && nobookSdkReady() && sha256(fs.readFileSync(nobookSdkPath)) === expected.toLowerCase());
  };
  const nobookExperimentUrlValid = () => validateExternalLabUrl('nobook', env.NOBOOK_EXPERIMENT_URL).ok;
  const nobookConfigured = () => nobookPartnerConfigured() && nobookSdkReady() && nobookSdkChecksumValid() && nobookExperimentUrlValid();

  async function nobookAuth(uniqueId) {
    const appKey = env.NOBOOK_APP_KEY, appSecret = env.NOBOOK_APP_SECRET, pidScope = env.NOBOOK_PID_SCOPE, version = env.NOBOOK_SDK_VERSION || '2.2.1';
    const timestamp = Math.round(Date.now() / 1000);
    const sign = crypto.createHash('md5').update(`${appKey}${appSecret}${pidScope}${timestamp}${uniqueId}${version}`).digest('hex');
    const authUrl = env.NOBOOK_AUTH_URL || 'https://nbapi.nobook.com/v1/auth';
    if (!validateExternalLabUrl('nobook', authUrl).ok) throw apiError(S.SERVICE_UNAVAILABLE, 'NOBOOK_CONFIGURATION_INVALID', 'Partner endpoint is not on the approved host list.');
    let response;
    try {
      response = await fetchImpl(authUrl, {method: 'POST', headers: {'Content-Type': 'application/json', Accept: 'application/json'}, body: JSON.stringify({app_key: appKey, pid_scope: pidScope, timestamp, unique_id: uniqueId, version, sign}), signal: AbortSignal.timeout(8000)});
    } catch {
      throw apiError(S.BAD_GATEWAY, 'UPSTREAM_UNAVAILABLE', 'Partner lab provider did not respond.');
    }
    if (!response.ok) throw apiError(S.BAD_GATEWAY, 'UPSTREAM_REJECTED', `Partner lab provider returned ${response.status}.`);
    await response.json().catch(() => ({}));
    return true; // The partner token is never forwarded to the browser.
  }

  // ---------- request helpers ----------
  function clientKey(req) { return req.socket.remoteAddress ?? 'unknown'; }
  function allowedOrigins(req) {
    const set = new Set(String(env.KIMYOLAB_ALLOWED_ORIGINS ?? '').split(',').map((x) => x.trim()).filter(Boolean));
    if (req.headers.host) { set.add(`http://${req.headers.host}`); set.add(`https://${req.headers.host}`); }
    return set;
  }
  async function readJsonBody(req, limit) {
    const declared = Number(req.headers['content-length']);
    if (Number.isFinite(declared) && declared > limit) throw apiError(S.PAYLOAD_TOO_LARGE, 'PAYLOAD_TOO_LARGE', `Request body exceeds ${limit} bytes.`);
    const chunks = []; let size = 0;
    for await (const chunk of req) {
      size += chunk.length;
      if (size > limit) throw apiError(S.PAYLOAD_TOO_LARGE, 'PAYLOAD_TOO_LARGE', `Request body exceeds ${limit} bytes.`);
      chunks.push(chunk);
    }
    if (!size) throw apiError(S.BAD_REQUEST, 'BODY_REQUIRED', 'A JSON body is required.');
    try { return JSON.parse(Buffer.concat(chunks).toString('utf8')); }
    catch { throw apiError(S.BAD_REQUEST, 'JSON_INVALID', 'Request body is not valid JSON.'); }
  }
  function rateLimit(limiter, req, route) {
    const verdict = limiter.take(`${clientKey(req)}|${route}`);
    if (!verdict.allowed) throw apiError(S.RATE_LIMITED, 'RATE_LIMITED', 'Too many requests.', {'Retry-After': String(verdict.retryAfterSeconds)});
  }

  // ---------- API ----------
  const routes = {
    'GET /api/external-labs/nobook/status': (req) => {
      rateLimit(limiters.status, req, 'status');
      return {status: 200, body: {configured: nobookConfigured(), partnerConfigured: nobookPartnerConfigured(), sdkReady: nobookSdkReady(), sdkChecksumValid: nobookSdkChecksumValid(), experimentUrlValid: nobookExperimentUrlValid(), sdkVersion: env.NOBOOK_SDK_VERSION || '2.2.1'}};
    },
    'GET /api/external-labs/status': (req) => {
      rateLimit(limiters.status, req, 'status');
      return {status: 200, body: {providers: {nobook: {configured: nobookConfigured(), partnerConfigured: nobookPartnerConfigured(), sdkReady: nobookSdkReady(), sdkChecksumValid: nobookSdkChecksumValid(), experimentUrlValid: nobookExperimentUrlValid()}, chemai: {configured: true, mode: 'deep-link'}, 'chem-lab-station': {configured: true, mode: 'reference'}}}};
    },
    'POST /api/external-labs/nobook/session': async (req) => {
      rateLimit(limiters.session, req, 'session');
      const origin = req.headers.origin;
      if (!origin) throw apiError(S.FORBIDDEN, 'ORIGIN_REQUIRED', 'Cross-origin protection requires an Origin header.');
      if (!allowedOrigins(req).has(origin)) throw apiError(S.FORBIDDEN, 'ORIGIN_FORBIDDEN', 'Origin is not allowed.');
      if (!/^application\/json(;|$)/i.test(String(req.headers['content-type'] ?? ''))) throw apiError(S.BAD_REQUEST, 'CONTENT_TYPE_UNSUPPORTED', 'Content-Type must be application/json.');
      const body = await readJsonBody(req, SESSION_BODY_LIMIT);
      if (typeof body !== 'object' || body === null || Array.isArray(body)) throw apiError(S.BAD_REQUEST, 'JSON_OBJECT_REQUIRED', 'Request body must be a JSON object.');
      const unknown = Object.keys(body).filter((k) => !(k in ID_PATTERNS));
      if (unknown.length) throw apiError(S.UNPROCESSABLE, 'REQUEST_FIELD_NOT_ALLOWED', `Unexpected field(s): ${unknown.join(', ')}. Provider and module are derived from the content binding.`);
      for (const [key, pattern] of Object.entries(ID_PATTERNS)) {
        if (typeof body[key] !== 'string' || !pattern.test(body[key])) throw apiError(S.UNPROCESSABLE, 'REQUEST_FIELD_INVALID', `${key} is missing or malformed.`);
      }
      const binding = loadActiveBindings().find((b) => b.id === body.bindingId);
      if (!binding) throw apiError(S.UNPROCESSABLE, 'BINDING_UNKNOWN', 'bindingId is not part of the active content pack.');
      if (binding.provider !== 'nobook') throw apiError(S.UNPROCESSABLE, 'BINDING_PROVIDER_MISMATCH', 'Binding does not belong to the NOBOOK provider.');
      if (binding.status === 'disabled') throw apiError(S.UNPROCESSABLE, 'BINDING_DISABLED', 'Binding is disabled.');
      if (!binding.learningUnitIds.includes(body.learningUnitId)) throw apiError(S.UNPROCESSABLE, 'BINDING_LEARNING_UNIT_MISMATCH', 'learningUnitId is not bound to this lab.');
      if (!nobookConfigured()) throw apiError(S.SERVICE_UNAVAILABLE, 'NOBOOK_PARTNER_CONFIGURATION_REQUIRED', 'Partner lab is not configured on this deployment.');
      const identityKey = env.NOBOOK_IDENTITY_KEY || crypto.createHmac('sha256', env.NOBOOK_APP_SECRET).update('kimyolab-nobook-identity-key-v1').digest();
      await nobookAuth(deriveNobookUniqueId(body.learnerRef, identityKey));
      const experimentUrl = validateExternalLabUrl('nobook', env.NOBOOK_EXPERIMENT_URL);
      return {status: 200, body: {experimentalUrl: experimentUrl.url, moduleId: binding.nobookModuleId, bindingId: binding.id}};
    },
  };
  const knownApiPaths = new Set(Object.keys(routes).map((k) => k.split(' ')[1]));

  async function handleApi(req, res, pathname, requestId) {
    const started = Date.now();
    let status = 500, code = 'INTERNAL_ERROR', extraHeaders = {};
    let payload;
    try {
      const handler = routes[`${req.method} ${pathname}`];
      if (!handler) {
        if (knownApiPaths.has(pathname)) {
          const allow = Object.keys(routes).filter((k) => k.endsWith(` ${pathname}`)).map((k) => k.split(' ')[0]).join(', ');
          throw apiError(S.METHOD_NOT_ALLOWED, 'METHOD_NOT_ALLOWED', 'Method not allowed.', {Allow: allow});
        }
        throw apiError(S.NOT_FOUND, 'API_NOT_FOUND', 'Unknown API endpoint.');
      }
      const result = await handler(req);
      status = result.status; code = 'OK'; payload = result.body;
    } catch (error) {
      if (error instanceof ApiError) { status = error.status; code = error.code; extraHeaders = error.headers; payload = {code: error.code, message: error.message, requestId}; }
      else { status = 500; code = 'INTERNAL_ERROR'; payload = {code, message: 'Internal server error.', requestId}; log({level: 'error', requestId, event: 'API_UNHANDLED', error: error instanceof Error ? error.message : String(error)}); }
    }
    if (!res.headersSent) {
      res.writeHead(status, headers({'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'X-Request-Id': requestId, ...extraHeaders}));
      res.end(JSON.stringify(payload));
    }
    if (req.readableEnded === false) req.resume();
    log({level: status >= 500 ? 'error' : status >= 400 ? 'warn' : 'info', requestId, method: req.method, route: pathname, status, code, ms: Date.now() - started});
  }

  // ---------- static (allow-list) ----------
  function notFound(res) { res.writeHead(404, headers({'Content-Type': 'text/plain; charset=utf-8'})); res.end('Not found'); }

  function resolveStatic(pathname) {
    if (SPA_EXACT.has(pathname) || SPA_PREFIXES.some((p) => pathname.startsWith(p))) return '/index.html';
    const ext = path.posix.extname(pathname).toLowerCase();
    if (!Object.hasOwn(TYPES, ext)) return undefined;
    if (ROOT_FILES.has(pathname)) return pathname;
    if (!PUBLIC_PREFIXES.some((p) => pathname.startsWith(p))) return undefined;
    if (ext === '.html') return undefined;
    if (pathname.startsWith('/content/')) {
      const [, , version] = pathname.split('/');
      if (version !== 'manifest.json' && !servableContentVersions().has(version)) return undefined;
    }
    return pathname;
  }

  function serveStatic(req, res, pathname) {
    const logical = resolveStatic(pathname);
    if (!logical) return notFound(res);
    const candidate = path.join(publicRoot, ...logical.split('/').filter(Boolean));
    let real;
    try { real = fs.realpathSync(candidate); } catch { return notFound(res); }
    if (!real.startsWith(`${realPublicRoot}${path.sep}`)) return notFound(res);
    let stat;
    try { stat = fs.statSync(real); } catch { return notFound(res); }
    if (!stat.isFile()) return notFound(res);
    const immutable = /^\/content\/[^/]+\/.+/.test(logical) && !logical.endsWith('/manifest.json');
    res.writeHead(200, headers({'Content-Type': TYPES[path.extname(real).toLowerCase()], 'Content-Length': String(stat.size), 'Cache-Control': immutable ? 'public, max-age=31536000, immutable' : 'no-cache'}));
    if (req.method === 'HEAD') return res.end();
    fs.createReadStream(real).on('error', () => res.destroy()).pipe(res);
  }

  return http.createServer(async (req, res) => {
    const requestId = crypto.randomUUID();
    const rawUrl = req.url ?? '/';
    if (rawUrl.length > MAX_URL_LENGTH) { res.writeHead(400, headers({'Content-Type': 'text/plain; charset=utf-8'})); res.end('Bad request'); return; }
    const rawPath = rawUrl.split('?')[0].split('#')[0];
    let pathname;
    try { pathname = decodeURIComponent(rawPath); } catch { res.writeHead(400, headers({'Content-Type': 'text/plain; charset=utf-8'})); res.end('Bad request'); return; }
    if (pathname.startsWith('/api/')) return handleApi(req, res, pathname, requestId);
    if (req.method !== 'GET' && req.method !== 'HEAD') { res.writeHead(405, headers({Allow: 'GET, HEAD', 'Content-Type': 'text/plain; charset=utf-8'})); res.end('Method not allowed'); return; }
    // Reject traversal, backslashes, NUL, dot-segments and dotfiles before touching the filesystem.
    const segments = pathname.split('/');
    if (!pathname.startsWith('/') || /[\\\0]/.test(pathname) || /%/.test(pathname) || segments.some((s) => s === '..' || s === '.' || (s.startsWith('.') && s.length > 0))) return notFound(res);
    serveStatic(req, res, pathname);
  });
}
